// MatchModal.tsx
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import {
  Button,
  Modal,
  Row,
  Col,
  ListGroup,
  Badge,
  ButtonGroup,
} from "react-bootstrap";
import type { Player } from "../types/types";

interface Props {
  show: boolean;
  onHide: () => void;
  team1: Player[];
  team2: Player[];
  onRegenerate: (mode: "balanced" | "random") => void;
}

const MatchModal = ({
  show,
  onHide,
  team1: initialT1,
  team2: initialT2,
  onRegenerate,
}: Props) => {
  const [localT1, setLocalT1] = useState<Player[]>([]);
  const [localT2, setLocalT2] = useState<Player[]>([]);
  const [mode, setMode] = useState<"balanced" | "random">("balanced");
  const navigate = useNavigate();

  useEffect(() => {
    setLocalT1(initialT1);
    setLocalT2(initialT2);
  }, [initialT1, initialT2]);

  const getPlayerOverall = (p: Player) => {
    const stats = Object.values(p.ratings || {});
    if (stats.length === 0) return 0;
    return Math.round(stats.reduce((a, b) => a + b, 0) / stats.length);
  };

  const calcAvg = (team: Player[]) => {
    if (team.length === 0) return 0;
    const total = team.reduce((acc, p) => acc + getPlayerOverall(p), 0);
    return Math.round(total / team.length);
  };

  const handleModeChange = (newMode: "balanced" | "random") => {
    setMode(newMode);
    onRegenerate(newMode);
  };

  const movePlayer = (player: Player, fromTeam: 1 | 2) => {
    if (fromTeam === 1) {
      setLocalT1(
        localT1.filter((p) => (p._id || p.id) !== (player._id || player.id))
      );
      setLocalT2([...localT2, player]);
    } else {
      setLocalT2(
        localT2.filter((p) => (p._id || p.id) !== (player._id || player.id))
      );
      setLocalT1([...localT1, player]);
    }
  };

  const generateShareText = () => {
    const formatList = (team: Player[]) =>
      team
        .map(
          (p) =>
            `• ${p.diskiName || p.name} (${p.position}) - *${getPlayerOverall(
              p
            )}*`
        )
        .join("\n");

    const text =
      `⚽ *Today's Match Lineups* ⚽\n\n` +
      `🟢 *TEAM 1* (Avg: ${calcAvg(localT1)})\n${formatList(localT1)}\n\n` +
      `🔴 *TEAM 2* (Avg: ${calcAvg(localT2)})\n${formatList(localT2)}\n\n` +
      `Generated by DiskiRater`;

    navigator.clipboard.writeText(text);
    alert("Lineups copied!");
  };

  const handleStartMatch = () => {
    // 1. Close the modal first
    onHide();

    navigate("/log-match", {
      state: {
        team1: localT1,
        team2: localT2,
      },
    });
  };

  return (
    <Modal show={show} onHide={onHide} size="lg" centered scrollable>
      <Modal.Header closeButton className="border-0 pb-0">
        <Modal.Title className="fw-bold">Match Setup</Modal.Title>
      </Modal.Header>

      <Modal.Body className="bg-light pt-0">
        <div className="d-flex justify-content-center my-3">
          <ButtonGroup className="shadow-sm bg-white rounded-pill p-1 border">
            <Button
              variant={mode === "balanced" ? "success" : "white"}
              className={`rounded-pill px-4 fw-bold border-0 ${
                mode !== "balanced" ? "text-muted" : ""
              }`}
              onClick={() => handleModeChange("balanced")}
            >
              ⚖️ Balanced
            </Button>
            <Button
              variant={mode === "random" ? "primary" : "white"}
              className={`rounded-pill px-4 fw-bold border-0 ${
                mode !== "random" ? "text-muted" : ""
              }`}
              onClick={() => handleModeChange("random")}
            >
              🎲 Random
            </Button>
          </ButtonGroup>
        </div>

        <Row className="g-2">
          <TeamColumn
            title="Team 1"
            players={localT1}
            avg={calcAvg(localT1)}
            color="success"
            onMove={(p: Player) => movePlayer(p, 1)}
            getPlayerOverall={getPlayerOverall}
          />
          <TeamColumn
            title="Team 2"
            players={localT2}
            avg={calcAvg(localT2)}
            color="danger"
            onMove={(p: Player) => movePlayer(p, 2)}
            getPlayerOverall={getPlayerOverall}
          />
        </Row>
      </Modal.Body>

      <Modal.Footer className="justify-content-between border-0 bg-light px-4 pb-4">
        <Button
          variant="outline-secondary"
          className="rounded-pill px-3"
          onClick={() => onRegenerate(mode)}
        >
          🔄 Re-Shuffle
        </Button>
        <div className="d-flex gap-2">
          <Button
            variant="warning"
            className="fw-bold px-4 rounded-pill shadow-sm"
            onClick={generateShareText}
          >
            Copy Lineups 📱
          </Button>
          <Button
            variant="success"
            className="fw-bold px-4 rounded-pill shadow-sm"
            onClick={handleStartMatch}
          >
            Start Match ⚽
          </Button>
        </div>
      </Modal.Footer>
    </Modal>
  );
};

// This was missing in the previous snippet, causing the "Cannot find name" error
const TeamColumn = ({
  title,
  players,
  avg,
  color,
  onMove,
  getPlayerOverall,
}: any) => (
  <Col xs={6}>
    <div
      className={`text-center mb-3 p-2 bg-${color} text-white rounded shadow-sm border border-2 border-white`}
    >
      <h6 className="mb-0 fw-bold">{title.toUpperCase()}</h6>
      <Badge bg="white" text="dark" className="mt-1">
        Strength: {avg}
      </Badge>
    </div>
    <ListGroup variant="flush" className="rounded shadow-sm overflow-hidden">
      {players.map((p: Player) => (
        <ListGroup.Item
          key={p?._id || p.id}
          className="d-flex justify-content-between align-items-center px-2 py-2"
        >
          <div className="d-flex align-items-center">
            <Button
              variant="link"
              className="p-0 me-2 text-decoration-none"
              onClick={() => onMove(p)}
              style={{ fontSize: "1rem" }}
            >
              {title === "Team 1" ? "➡️" : "⬅️"}
            </Button>
            <div
              className="d-flex flex-column text-truncate"
              style={{ maxWidth: "80px" }}
            >
              <span
                className="fw-bold text-truncate"
                style={{ fontSize: "0.85rem" }}
              >
                {p.diskiName || p.name}
              </span>
              <small
                className="text-muted text-truncate"
                style={{ fontSize: "0.65rem" }}
              >
                {p.position}
              </small>
            </div>
          </div>
          <Badge bg="light" text="dark" className="border fw-bold">
            {getPlayerOverall(p)}
          </Badge>
        </ListGroup.Item>
      ))}
    </ListGroup>
  </Col>
);

export default MatchModal;
